# Touch get started

In [2]:
import pandas as pd

data = pd.read_parquet('feature_repo/data/driver_stats.parquet')
data.head(10)

,event_timestamp,driver_id,conv_rate,acc_rate,avg_daily_trips,created
0,2025-12-08 17:00:00+00:00,1005,0.329265,0.473247,54,2025-12-23 17:06:58.100
1,2025-12-08 18:00:00+00:00,1005,0.263852,0.113851,878,2025-12-23 17:06:58.100
2,2025-12-08 19:00:00+00:00,1005,0.217522,0.237648,823,2025-12-23 17:06:58.100
3,2025-12-08 20:00:00+00:00,1005,0.993969,0.325710,463,2025-12-23 17:06:58.100
4,2025-12-08 21:00:00+00:00,1005,0.286329,0.492599,389,2025-12-23 17:06:58.100
5,2025-12-08 22:00:00+00:00,1005,0.535928,0.498069,126,2025-12-23 17:06:58.100
6,2025-12-08 23:00:00+00:00,1005,0.772512,0.333633,656,2025-12-23 17:06:58.100
7,2025-12-09 00:00:00+00:00,1005,0.306284,0.827252,200,2025-12-23 17:06:58.100
8,2025-12-09 01:00:00+00:00,1005,0.497023,0.074246,432,2025-12-23 17:06:58.100
9,2025-12-09 02:00:00+00:00,1005,0.278861,0.250249,833,2025-12-23 17:06:58.100

In [3]:
data.driver_id.unique()

array([1005, 1004, 1003, 1002, 1001])

In [4]:
data.event_timestamp[:3]

0   2025-12-08 17:00:00+00:00
1   2025-12-08 18:00:00+00:00
2   2025-12-08 19:00:00+00:00
Name: event_timestamp, dtype: datetime64[ns, UTC]

In [5]:
from datetime import datetime
import pandas as pd

from feast import FeatureStore


entity_df = pd.DataFrame.from_dict(
    {

        "driver_id": [1005, 1004, 1003],
        "event_timestamp": [
            datetime(2025, 12, 8, 17, 0, 0),
            datetime(2025, 12, 8, 18, 0, 0),
            datetime(2025, 12, 8, 19, 0, 0),
        ],

        "label_driver_reported_satisfaction": [1, 5, 3],

        "val_to_add": [1, 2, 3],
        "val_to_add_2": [10, 20, 30],
    }
)

entity_df.head()

/Users/artem.pereverzev/reps/artem-pereverzev-bivt-22-16/.venv/lib/python3.12/site-packages/feast/permissions/auth_model.py:35: PydanticDeprecatedSince212: Using `@model_validator` with mode='after' on a classmethod is deprecated. Instead, use an instance method. See the documentation at https://docs.pydantic.dev/2.12/concepts/validators/#model-after-validator. Deprecated in Pydantic V2.12 to be removed in V3.0.
  @model_validator(mode="after")

,driver_id,event_timestamp,label_driver_reported_satisfaction,val_to_add,val_to_add_2
0,1005,2025-12-08 17:00:00,1,1,10
1,1004,2025-12-08 18:00:00,5,2,20
2,1003,2025-12-08 19:00:00,3,3,30

In [11]:
store = FeatureStore(repo_path="feature_repo")

training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
        "transformed_conv_rate:conv_rate_plus_val1",
        "transformed_conv_rate:conv_rate_plus_val2",
    ],
).to_df()


training_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 10 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   driver_id                           3 non-null      int64
 1   event_timestamp                     3 non-null      datetime64[ns, UTC]
 2   label_driver_reported_satisfaction  3 non-null      int64
 3   val_to_add                          3 non-null      int64
 4   val_to_add_2                        3 non-null      int64
 5   conv_rate                           3 non-null      float32
 6   acc_rate                            3 non-null      float32
 7   avg_daily_trips                     3 non-null      int32
 8   conv_rate_plus_val1                 3 non-null      float64
 9   conv_rate_plus_val2                 3 non-null      float64
dtypes: datetime64[ns, UTC](1), float32(2), float64(2), int32(1), int64(4)
memory usage: 336.0 bytes

In [12]:
training_df.head()

,driver_id,event_timestamp,label_driver_reported_satisfaction,val_to_add,val_to_add_2,conv_rate,acc_rate,avg_daily_trips,conv_rate_plus_val1,conv_rate_plus_val2
0,1005,2025-12-23 14:29:21.026121+00:00,1,1,10,0.015227,0.776826,27,1.015227,10.015227
1,1004,2025-12-23 14:29:21.026121+00:00,5,2,20,0.516371,0.970697,447,2.516371,20.516371
2,1003,2025-12-23 14:29:21.026121+00:00,3,3,30,0.036170,0.355659,615,3.036170,30.036170

In [8]:
entity_df["event_timestamp"] = pd.to_datetime("now", utc=True)
training_df = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
        "transformed_conv_rate:conv_rate_plus_val1",
        "transformed_conv_rate:conv_rate_plus_val2",
    ],
).to_df()


training_df.head()

,driver_id,event_timestamp,label_driver_reported_satisfaction,val_to_add,val_to_add_2,conv_rate,acc_rate,avg_daily_trips,conv_rate_plus_val1,conv_rate_plus_val2
0,1005,2025-12-23 14:29:21.026121+00:00,1,1,10,0.015227,0.776826,27,1.015227,10.015227
1,1004,2025-12-23 14:29:21.026121+00:00,5,2,20,0.516371,0.970697,447,2.516371,20.516371
2,1003,2025-12-23 14:29:21.026121+00:00,3,3,30,0.036170,0.355659,615,3.036170,30.036170

In [9]:
feature_vector = store.get_online_features(
    features=[
        "driver_hourly_stats:conv_rate",
        "driver_hourly_stats:acc_rate",
        "driver_hourly_stats:avg_daily_trips",
    ],
    entity_rows=[
        # {join_key: entity_value}
        {"driver_id": 1004},
        {"driver_id": 1005},
    ],
).to_dict()

print(feature_vector)

{'driver_id': [1004, 1005], 'avg_daily_trips': [None, None], 'conv_rate': [None, None], 'acc_rate': [None, None]}